### PR TITLE
Keep track of horizontal direction while drawing

### LINKED ISSUE #7: Arrows on paths can point into wrong direction
As demonstrated in [example 12, near the `compound-operator`](https://htmlpreview.github.io/?https://github.com/lukaslueg/railroad_dsl/blob/master/examples/example_diagrams.html): There is a corner case where the direction the path-arrows point to is wrong: Each primitive simply assumes the global, general direction "left to right, top to bottom". This is not true for the separator in a `Repeat`-Element, which is the only place where things are "right to left". Since that element can be any `RailroadNode`, it can include arrows which will point "left to right" instead of "right to left".

We can ignore this as a quirk for some time. Eventually each primitive needs a knob that tells it about the reading-direction.

### PR DESCRIPTION
**Pull request by birkenfeld**
Open points:

- Is this strategy good? Is it enough? Entry/Exit in a node haven't changed meaning.
- I thought about the nodes knowing their own reading direction, but that would become cumbersome since `Repeat` then has to change the direction of its entire subtree when constructed.
- Start/End now assert LTR direction, since otherwise their meaning would be reversed. Is it necessary?

Fixes #7

### CODE REVIEW

**Comment by lukaslueg** [comment]
Thanks for the pull request! There are two unrelated commits here:

* I'm also unsure about the strategy here. It feels wrong that a problem that concerns only `Repeat` leaks into every single possible `impl RailroadNode`; this is demonstrated by some impls simply ignoring the argument. Since I don't have a better idea, I guess we can proceed anyway. The `assert` on Start/End are a trap, nobody protects one from constructing nonsense diagrams (e.g. `Sequence(Start, Start, End, Start, End)`) anyway, and should be removed.
* The Correct Way™ to implement multiline text in SVG is [`<tspan>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan), where we control the placement of each line separately. Apparently only some SVG implementors render a wild line break at all. The way to do this is probably similar to `PathData`, where we have a `<text>`-builder that takes lines, constructs `<tspan>`s for each line which are proceedingly offset (via `dy`) according to our secret knowledge of the text height, and spits out the final `<text>...</text>`.

Just let me know how you want to proceed; 613e662 should not be merged, I could do the text thing in the next couple of days.

**Comment by birkenfeld** [comment]
The text change wasn't supposed to be in here, I didn't consider github auto-updating pull requests... Will rework it to use `<tspan>` before making one.

**Comment by lukaslueg** [comment]
I've pushed some verification infrastructure which should help to determine if we are doing it correctly at least according to spec. Use `visuals.rs` and `visual-debug` to verify that each `tspan` is placed visually correct.

**Comment by birkenfeld** [comment]
Great! While I'm working on the text thing, I guess we'll want to support multiline text for all elements, not just `Comment`?

**Comment by lukaslueg** [comment]
Yeah, but the signature should move from `String` to `Into<svg::TextArea>` where we have impls for `&str` and `[&str]`, where the slice-thing is multilined. Does that make sense?

**Comment by lukaslueg** [comment]
Oh and don't forget that each `tspan` must have it's content escaped, or `Foo<bar>` will leak into the markup :-)

**Comment by birkenfeld** [comment]
Sounds good.

**Comment by birkenfeld** [comment]
Ok, this PR is cleaned up now.

As for the leaking into unrelated nodes, the only alternative I saw was to add an API on `RailroadNode` to change direction, which also leaks into all node impls, so I didn't consider it better from that viewpoint.

**Comment by birkenfeld** [comment]
BTW, why are the verification tests `#[ignore]`d?

**Comment by lukaslueg** [comment]
Because they use `xmllint` from libxml2, which may not be available to everyone that runs "cargo test".

**Comment by lukaslueg** [comment]
Could you remove the `assert` and make a PR for just that commit? It's unrelated to the `text`-thing

**Comment by birkenfeld** [comment]
I had already updated my master (and therefore this PR) to just include that commit, with the asserts removed. Is anything else required?

**Comment by birkenfeld** [comment]
Thanks!

**Comment by lukaslueg** [comment]
One could argue that the reading direction should also cause primitives to be placed differently. Again in [example 12](https://htmlpreview.github.io/?https://github.com/lukaslueg/railroad_dsl/blob/master/examples/example_diagrams.html), while the arrow is now pointing correctly, the separator should be right-aligned, not left-aligned. This is a nitpick, however, and can be left for another day.

Thanks for the PR!

**Pull request merged**
